# Generated by Django 4.0.3 on 2022-04-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGithubOauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveSmallIntegerField()),
                ('access_token', models.CharField(max_length=100)),
            ],
        ),
    ]
