# Generated by Django 4.0.3 on 2022-04-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergithuboauth',
            name='uid',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
